ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'Soumil123' ;
FLUSH PRIVILEGES;

-- Exploratory Data Analysis (EDA) 
SELECT * FROM WALMART;

SELECT COUNT(*) FROM WALMART;

SELECT PAYMENT_METHOD,COUNT(*) FROM WALMART GROUP BY PAYMENT_METHOD;

SELECT COUNT(DISTINCT BRANCH) FROM WALMART;

-- BUSINESS PROBLEMS
-- Q1. What are the different payment methods, and how many transactions and items were sold with each method?
 
 SELECT PAYMENT_METHOD, 
  COUNT(*) AS NO_OF_TXN, 
  SUM(QUANTITY) AS NO_OF_QTY_SOLD 
  FROM  WALMART 
  GROUP BY PAYMENT_METHOD;

-- Q2. Which category received the highest average rating in each branch?
SELECT * FROM (
SELECT BRANCH,
 CATEGORY,
 AVG(RATING) AS AVG_RATING, 
 RANK() OVER(PARTITION BY BRANCH ORDER BY AVG(RATING) DESC) AS RANKING
 FROM WALMART 
 GROUP BY BRANCH, CATEGORY
 ) AS RANKING_AVG
 WHERE RANKING = 1 ORDER BY AVG_RATING DESC;
 
 -- Q3.  What is the busiest day of the week for each branch based on transaction volume?
SELECT * FROM
(
 SELECT BRANCH,
 DAYNAME(DATE) AS DAY, 
 COUNT(*) AS NO_OF_TXN, 
 RANK() OVER(PARTITION BY BRANCH ORDER BY COUNT(*) DESC) AS RANKING
 FROM WALMART 
 GROUP BY BRANCH,DAYNAME(DATE)
) AS BRANCH_TXN
WHERE RANKING = 1;

-- Q4. How many items were sold through each payment method?
SELECT PAYMENT_METHOD, 
SUM(QUANTITY) AS QTY_SOLD 
FROM WALMART 
GROUP BY PAYMENT_METHOD;

-- Q5. What are the average, minimum, and maximum ratings for each category in each city?
SELECT CITY, CATEGORY, 
AVG(RATING) AS AVG_RATING, 
MIN(RATING) AS MIN_RATING, 
MAX(RATING) AS MAX_RATING 
FROM WALMART 
GROUP BY CITY, CATEGORY;

-- Q6.  What is the total profit for each category, ranked from highest to lowest?
SELECT CATEGORY,
SUM(TOTAL_PRICE) AS T0TAL_REVENUE, 
SUM((UNIT_PRICE * PROFIT_MARGIN) * QUANTITY) AS TOTAL_PROFIT 
FROM WALMART 
GROUP BY CATEGORY 
ORDER BY TOTAL_PROFIT DESC;

-- Q7. What is the most frequently used payment method in each branch?
SELECT * FROM
(
SELECT BRANCH, 
PAYMENT_METHOD, 
COUNT(*) AS TOTAL_TXN, 
RANK() OVER(PARTITION BY BRANCH ORDER BY COUNT(*) DESC) AS RANKING
FROM WALMART 
GROUP BY BRANCH, PAYMENT_METHOD
) MOST_USED_PAYMENT_METHOD
WHERE RANKING = 1 ;

-- Q8. How many transactions occur in each shift (Morning, Afternoon, Evening) across branches?
SELECT BRANCH,
COUNT(*) AS NO_OF_TXN, 
CASE WHEN HOUR(TIME) < 12 THEN 'MORNING'
WHEN HOUR(TIME) >= 12 AND HOUR(TIME) <= 17 THEN 'AFTERNOON'
ELSE 'EVENING'
END AS SHIFT
FROM WALMART 
GROUP BY SHIFT, BRANCH 
ORDER BY BRANCH, NO_OF_TXN DESC;

-- Q9. Which branches experienced the largest decrease in revenue compared to the previous year?



-- 2022 SALES
WITH REVENUE_2022 AS
(SELECT BRANCH, SUM(TOTAL_PRICE) AS REVENUE FROM WALMART WHERE YEAR(DATE) = 2022 GROUP BY BRANCH),

-- 2023 SALES
REVENUE_2023 AS
(SELECT BRANCH, SUM(TOTAL_PRICE) AS REVENUE FROM WALMART WHERE YEAR(DATE) = 2023 GROUP BY BRANCH)

SELECT LYS.BRANCH, 
LYS.REVENUE AS LAST_YEAR_REVENUE, 
CYS.REVENUE AS CURRENT_YEAR_REVENUE,
(CYS.REVENUE - LYS.REVENUE) AS REVENUE_CHANGE,
CONCAT(ROUND(((CYS.REVENUE - LYS.REVENUE) / LYS.REVENUE) * 100, 2), '%') AS PERCENT_DECREASED
FROM REVENUE_2022 AS LYS 
JOIN
REVENUE_2023 AS CYS 
ON LYS.BRANCH = CYS.BRANCH 
WHERE LYS.REVENUE > CYS.REVENUE 
ORDER BY REVENUE_CHANGE ASC LIMIT 5;


